In [1]:
import pandas as pd

df = pd.read_csv("cleaned_global_ecommerce_sales.csv")
df.head()

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11746,2023-01-05,Fatima Suzuki,Consumer,Mexico,North America,Furniture,Bookshelf 5-Tier,1,61.93,10,55.74,5.88,12.70,PayPal

In [2]:
import pandas as pd
import sqlite3

In [3]:
conn = sqlite3.connect("ecommerce.db")

In [4]:
df.to_sql("sales", conn, if_exists="replace", index=False)

1810

In [5]:
pd.read_sql("SELECT * FROM sales LIMIT 5;", conn)

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11746,2023-01-05,Fatima Suzuki,Consumer,Mexico,North America,Furniture,Bookshelf 5-Tier,1,61.93,10,55.74,5.88,12.70,PayPal

SELECT

In [6]:
query = """
SELECT * FROM sales;
"""

pd.read_sql(query, conn)

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11746,2023-01-05,Fatima Suzuki,Consumer,Mexico,North America,Furniture,Bookshelf 5-Tier,1,61.93,10,55.74,5.88,12.70,PayPal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,ORD-11814,2025-12-30,Jennifer Oliveira,Consumer,India,Asia Pacific,Furniture,Filing Cabinet 3-Drawer,1,177.90,10,160.11,10.23,43.14,PayPal
1806,ORD-10823,2025-12-31,Linda Nilsson,Consumer,France,Europe,Furniture,Folding Table Portable,5,104.73,0,523.65,19.10,190.36,PayPal
1807,ORD-11148,2025-12-31,Barbara Jones,Consumer,Spain,Europe,Technology,Webcam HD 1080p,6,31.79,15,162.13,15.19,42.03,Bank Transfer
1808,ORD-11519,2025-12-31,Maria Suzuki,Home Office,Spain,Europe,Clothing & Accessories,Sports Water Bottle 750ml,5,9.50,5,45.12,14.25,7.12,Credit Card
1809,ORD-11701,2025-12-31,Susan Russo,Home Office,South Korea,Asia Pacific,Clothing & Accessories,Sports Water Bottle 750ml,11,28.27,0,310.97,36.23,119.26,Credit Card

WHERE

In [8]:
query = """
SELECT * FROM sales
WHERE total_sales > 500;
"""

pd.read_sql(query, conn)

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-10402,2023-01-14,Jamal Schmidt,Consumer,Mexico,North America,Furniture,Folding Table Portable,6,96.58,0,579.48,10.22,221.57,Credit Card
1,ORD-10594,2023-02-21,Ayumi Khan,Consumer,United States,North America,Technology,Smart LED Desk Lamp,8,72.89,0,583.12,14.27,248.13,Credit Card
2,ORD-10915,2023-03-08,Ahmed Harris,Consumer,Brazil,South America,Furniture,Floating Wall Shelves Set,6,99.69,0,598.14,18.01,221.25,Credit Card
3,ORD-10676,2023-03-17,Wei Chen,Consumer,Saudi Arabia,Middle East & Africa,Technology,Mechanical Gaming Keyboard,3,174.46,0,523.38,14.65,220.87,Credit Card
4,ORD-10071,2023-04-05,Richard Müller,Consumer,United States,North America,Furniture,Ergonomic Office Chair,2,252.68,0,505.36,8.12,194.02,PayPal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,ORD-11608,2025-11-01,Isabella Sato,Consumer,Argentina,South America,Clothing & Accessories,Travel Backpack 30L,6,92.98,0,557.88,18.67,260.27,PayPal
63,ORD-11256,2025-11-03,Ivan Sato,Consumer,Spain,Europe,Furniture,Corner L-Shaped Desk,2,297.84,15,506.33,8.55,140.37,Bank Transfer
64,ORD-11940,2025-11-03,Hanna Hassan,Home Office,France,Europe,Technology,Portable External SSD 1TB,6,110.54,10,596.92,21.12,211.02,PayPal
65,ORD-11693,2025-12-10,Carlos Rodriguez,Corporate,Brazil,South America,Furniture,Bookshelf 5-Tier,3,194.57,0,583.71,13.80,219.68,Credit Card
66,ORD-10823,2025-12-31,Linda Nilsson,Consumer,France,Europe,Furniture,Folding Table Portable,5,104.73,0,523.65,19.10,190.36,PayPal

ORDER BY

In [9]:
query = """
SELECT * FROM sales
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11422,2023-09-03,David Clark,Consumer,Germany,Europe,Furniture,Folding Table Portable,10,67.10,10,603.90,14.47,186.83,Cash on Delivery
1,ORD-10975,2025-01-04,Oscar Nilsson,Consumer,France,Europe,Furniture,Filing Cabinet 3-Drawer,5,127.03,5,603.39,16.49,205.81,PayPal
2,ORD-11795,2023-09-14,Ali Johnson,Corporate,Mexico,North America,Furniture,Monitor Riser Wood,14,61.54,30,603.09,33.58,52.57,Credit Card
3,ORD-10661,2023-06-29,Olga Nilsson,Consumer,Canada,North America,Technology,Webcam HD 1080p,9,74.43,10,602.88,11.59,222.86,Credit Card
4,ORD-11541,2025-09-23,Sarah Weber,Home Office,United States,North America,Furniture,Mesh Back Task Chair,6,118.21,15,602.87,11.16,166.15,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,ORD-11430,2023-02-04,Karen Martinez,Home Office,Colombia,South America,Office Supplies,Paper Clips Box 500pc,1,4.78,10,4.30,11.84,-9.69,Bank Transfer
1806,ORD-11269,2024-10-17,Sophie Johansson,Corporate,Saudi Arabia,Middle East & Africa,Office Supplies,Paper Clips Box 500pc,1,4.87,15,4.14,12.43,-10.48,Bank Transfer
1807,ORD-10407,2024-04-21,Isabella Laurent,Corporate,Germany,Europe,Office Supplies,Sticky Notes Multicolor 6-Pack,1,4.02,15,3.42,7.74,-6.13,Bank Transfer
1808,ORD-11662,2025-06-07,Jennifer Thompson,Corporate,Mexico,North America,Office Supplies,Paper Clips Box 500pc,1,3.44,25,2.58,6.69,-5.66,Credit Card
1809,ORD-11001,2025-02-20,Isabella Jackson,Corporate,Japan,Asia Pacific,Office Supplies,Paper Clips Box 500pc,1,3.03,20,2.42,11.16,-10.10,Cash on Delivery

LIMIT

In [10]:
query = """
SELECT * FROM sales
LIMIT 10;
"""

pd.read_sql(query, conn)

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11746,2023-01-05,Fatima Suzuki,Consumer,Mexico,North America,Furniture,Bookshelf 5-Tier,1,61.93,10,55.74,5.88,12.70,PayPal
5,ORD-11162,2023-01-06,Felix Rodriguez,Home Office,United States,North America,Office Supplies,Premium Notebook Set A5,2,15.03,5,28.56,6.59,8.44,PayPal
6,ORD-11271,2023-01-06,Ayumi Ferrari,Home Office,Nigeria,Middle East & Africa,Technology,Laptop Stand Adjustable,2,33.91,10,61.04,14.38,9.36,Bank Transfer
7,ORD-10847,2023-01-07,Ali Rodriguez,Consumer,Saudi Arabia,Middle East & Africa,Furniture,Folding Table Portable,1,58.77,5,55.83,12.03,8.54,Credit Card
8,ORD-10446,2023-01-08,Raj Martinez,Corporate,Colombia,South America,Clothing & Accessories,Leather Wallet Minimalist,2,38.91,15,66.15,14.25,12.99,Credit Card
9,ORD-11499,2023-01-08,Kenji Rossi,Corporate,Spain,Europe,Office Supplies,Paper Clips Box 500pc,3,7.80,10,21.06,12.61,-2.08,Cash on Delivery

COUNT

In [11]:
query = """
SELECT COUNT(*) AS total_records
FROM sales;
"""

pd.read_sql(query, conn)

   total_records
0           1810

SUM

In [13]:
query = """
SELECT SUM(total_sales) AS total_sales
FROM sales;
"""

pd.read_sql(query, conn)

   total_sales
0    261284.78

AVERAGE

In [14]:
query = """
SELECT AVG(total_sales) AS average_sales
FROM sales;
"""

pd.read_sql(query, conn)

   average_sales
0     144.356232

GROUP BY

In [17]:
query = """
SELECT product_category,
SUM(total_sales) AS total_sales
FROM sales
GROUP BY product_category;
"""

pd.read_sql(query, conn)

         product_category  total_sales
0  Clothing & Accessories     57730.36
1               Furniture     90424.83
2         Office Supplies     19390.81
3              Technology     93738.78

In [18]:
df.columns.tolist()

['order_id',
 'order_date',
 'customer_name',
 'customer_segment',
 'country',
 'region',
 'product_category',
 'product_name',
 'quantity',
 'unit_price',
 'discount_percent',
 'total_sales',
 'shipping_cost',
 'profit',
 'payment_method']