In [ ]:
import pandas as pd
import sqlite3
df = pd.read_csv("cleaned_global_ecommerce_sales.csv")
df.head()

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11746,2023-01-05,Fatima Suzuki,Consumer,Mexico,North America,Furniture,Bookshelf 5-Tier,1,61.93,10,55.74,5.88,12.70,PayPal

In [ ]:
conn = sqlite3.connect("ecommerce.db")

In [ ]:
df.to_sql("sales", conn, if_exists="replace", index=False)

1810

Display All Records

In [ ]:
query = "SELECT * FROM sales;"

result = pd.read_sql(query, conn)
result.head()

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11746,2023-01-05,Fatima Suzuki,Consumer,Mexico,North America,Furniture,Bookshelf 5-Tier,1,61.93,10,55.74,5.88,12.70,PayPal

Filter Records

In [ ]:
query = """
SELECT *
FROM sales
WHERE total_sales > 500;
"""

result = pd.read_sql(query, conn)
result.head()

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-10402,2023-01-14,Jamal Schmidt,Consumer,Mexico,North America,Furniture,Folding Table Portable,6,96.58,0,579.48,10.22,221.57,Credit Card
1,ORD-10594,2023-02-21,Ayumi Khan,Consumer,United States,North America,Technology,Smart LED Desk Lamp,8,72.89,0,583.12,14.27,248.13,Credit Card
2,ORD-10915,2023-03-08,Ahmed Harris,Consumer,Brazil,South America,Furniture,Floating Wall Shelves Set,6,99.69,0,598.14,18.01,221.25,Credit Card
3,ORD-10676,2023-03-17,Wei Chen,Consumer,Saudi Arabia,Middle East & Africa,Technology,Mechanical Gaming Keyboard,3,174.46,0,523.38,14.65,220.87,Credit Card
4,ORD-10071,2023-04-05,Richard Müller,Consumer,United States,North America,Furniture,Ergonomic Office Chair,2,252.68,0,505.36,8.12,194.02,PayPal

Category-wise Sales

In [ ]:
query = """
SELECT product_category,
SUM(total_sales) AS total_sales
FROM sales
GROUP BY product_category;
"""

result = pd.read_sql(query, conn)
result

         product_category  total_sales
0  Clothing & Accessories     57730.36
1               Furniture     90424.83
2         Office Supplies     19390.81
3              Technology     93738.78

Use a Parameterized Query

In [ ]:
sales_limit = 500

query = """
SELECT *
FROM sales
WHERE total_sales > ?;
"""

result = pd.read_sql(query, conn, params=[sales_limit])
result.head()

,order_id,order_date,customer_name,customer_segment,country,region,product_category,product_name,quantity,unit_price,discount_percent,total_sales,shipping_cost,profit,payment_method
0,ORD-10402,2023-01-14,Jamal Schmidt,Consumer,Mexico,North America,Furniture,Folding Table Portable,6,96.58,0,579.48,10.22,221.57,Credit Card
1,ORD-10594,2023-02-21,Ayumi Khan,Consumer,United States,North America,Technology,Smart LED Desk Lamp,8,72.89,0,583.12,14.27,248.13,Credit Card
2,ORD-10915,2023-03-08,Ahmed Harris,Consumer,Brazil,South America,Furniture,Floating Wall Shelves Set,6,99.69,0,598.14,18.01,221.25,Credit Card
3,ORD-10676,2023-03-17,Wei Chen,Consumer,Saudi Arabia,Middle East & Africa,Technology,Mechanical Gaming Keyboard,3,174.46,0,523.38,14.65,220.87,Credit Card
4,ORD-10071,2023-04-05,Richard Müller,Consumer,United States,North America,Furniture,Ergonomic Office Chair,2,252.68,0,505.36,8.12,194.02,PayPal

Save SQL Results to a CSV File

In [ ]:
result.to_csv("category_sales.csv", index=False)

This creates a file named category_sales.csv

In [10]:
conn.close()